### ISSUE TITLE
idea: issue creator action if workflow fails

### ISSUE THREAD

**Issue by RemcoHalman** [EddieHubCommunity/template#2]
In github actions there is the possibility to run a action if the run fails

[Github action](https://github.com/nashmaniac/create-issue-action) <- creates issue with labels and assignee

```yml
- uses: nashmaniac/create-issue-action@v1.1
  if: ${{ failure() }} # only run when this job is failed.
  name: Create Issue Action
  with:
    title: Linter Failed
    token: ${{secrets.GITHUB_TOKEN}}
    assignees: ${{github.actor}}
    labels: refactoring-needed, help needed
    body: Workflow failed for commit ${{github.sha}}
```
